%YAML 1.1
---

- name: validator deployment
  hosts: all:!local
  vars_prompt:
    - name: validator_vers
      prompt: response-validator version
      private: no
  become: no
  tags:
    - validator
  roles:
    - setup
    - gunicorn
    - nginx
