%YAML 1.1
---
#gunicorn_graylog_watch_files:
#  - path: "{{ application.directory }}/logs/access.log"
#    unique_name: "{{ application.name }}_gunicorn_access"
#  - path: "{{ application.directory }}/logs/access.log"
#    unique_name: "{{ application.name }}_gunicorn_error"
gunicorn:
  name: gunicorn.service
  user: validator
  group: validator
  gunicorn: /home/validator/venv/bin/gunicorn
  runtime_dir: gunicorn
  working_dir: /home/validator/validator
  sock_file: /run/gunicorn/gunicorn.sock
  files:
    - src: gunicorn.service.j2
      dest: /etc/systemd/system/gunicorn.service
    - src: gunicorn.socket.j2
      dest: /etc/systemd/system/gunicorn.socket
    - src: etc/defaults/gunicorn.j2
      dest: /etc/default/gunicorn
    - src: etc/tmpfiles.d/gunicorn.conf.j2
      dest: /etc/tmpfiles.d/gunicorn.conf
