# vim: ft=yaml syntax=yaml sts=2 ts=2 sw=2 nosr et nu ru
%YAML 1.1
---

- name: get validator revision
  command: "git --git-dir=/var/openstax-validator/response-validation/.git rev-parse HEAD@{0}"
  args:
    warn: no
  delegate_to: 127.0.0.1
  register: git_rev
  when:
    - validator_rev is undefined

- name: set validator version variable
  set_fact:
    version: "{{ git_rev.stdout }}"
  when:
    - git_rev is defined
    - git_rev['stdout'] is defined

- name: set validator version variable from alternate
  set_fact:
    version: "{{ validator_rev }}"
  when:
    - validator_rev is defined
