# vim: ft=yaml syntax=yaml sts=2 ts=2 sw=2 nosr et nu ru
%YAML 1.1
---
apt_packages:
  - nginx
  - virtualenv

user:
  name: validator
  group: validator
  home: /home/validator

main_dir: "{{ (playbook_dir ~ '/../') | realpath }}"
app_dir: "{{ user['home'] }}/validator"

sentry_dsn: "https://d587530fe7824275a726f6748c0c56c3@sentry.cnx.org/21"
