%YAML 1.1
---
ansible_python_interpreter: /usr/bin/python3
app:
  name: validator
  root: /var/www/html
  server_names:
    - "validator-{{ EnvName }}-ae.openstax.org"
    - "{{ inventory_hostname }}"
