%YAML 1.1
---

- name: install necessary apt packages
  become: yes
  apt:
    name: "{{ apt_packages }}"
    state: latest
    update_cache: yes
    install_recommends: yes
    autoclean: yes
  tags: apt-setup

- name: create user
  become: yes 
  user:
    home: "{{ user['home'] }}"
    name: "{{ user['name'] }}"
    state: present
  tags: user-setup

- name: virtualenv setup
  become: yes
  become_user: "{{ user['name'] }}"
  command: virtualenv -q -p python3 venv
  args:
    chdir: "{{ user['home'] }}"
  tags:
    - virtualenv
    - virtualenv-setup

- name: copy over validator repo
  become: yes
  synchronize:
    src: "{{ main_dir }}/validator/"
    dest: "{{ app_dir }}"
    set_remote_user: no
    use_ssh_args: yes
  tags:
    - validator-update

- name: fix permissions
  become: yes
  file:
    path: "{{ app_dir }}"
    owner: "{{ user['name'] }}"
    group: "{{ user['group'] }}"
    recurse: yes
  tags:
    - permissions
    - validator

- name: pip install requirements.txt
  become: yes
  become_user: "{{ user['name'] }}"
  pip:
    virtualenv: "{{ user['home'] }}/venv"
    requirements: "{{ app_dir }}/requirements.txt"
  tags:
    - validator-setup

- name: install additional modules
  become: yes
  become_user: "{{ user['name'] }}"
  command: "{{ user['home'] }}/venv/bin/python -m nltk.downloader {{ module }}"
  loop:
    - snowball_data
    - words
    - stopwords
  loop_control:
    loop_var: module
  tags:
    - validator-setup

- name: tag environment as configured
  become: no
  file:
    path: "{{ inventory_dir }}/.setup-complete"
    state: touch
  delegate_to: 127.0.0.1
  tags:
    - configure-confirm
