%YAML 1.1
---

- name: install necessary apt packages
  become: yes
  apt:
    name: "{{ apt_packages }}"
    state: present
    update_cache: yes
    install_recommends: yes
    autoclean: yes
  tags: apt-setup

- name: create user
  become: yes
  user:
    home: "{{ user['home'] }}"
    name: "{{ user['name'] }}"
    state: present
  tags: user-setup

- name: check for virtualenv
  become: yes
  stat:
    path: "{{ user['home'] }}/venv"
    follow: yes
    get_attributes: no
    get_checksum: no
  register: venv_check
  tags:
    - virtualenv
    - virtualenv-setup

- name: virtualenv setup
  become: yes
  become_user: "{{ user['name'] }}"
  shell: |
    virtualenv -q -p python3 venv
    venv/bin/python -m pip install --upgrade pip setuptools wheel
  when: not venv_check.stat.exists
  args:
    chdir: "{{ user['home'] }}"
  tags:
    - virtualenv
    - virtualenv-setup

- name: create app dir
  become: yes
  become_user: "{{ user['name'] }}"
  file:
    path: "{{ app_dir }}"
    state: directory

- name: tag environment as configured
  become: no
  file:
    path: "{{ inventory_dir }}/.setup-complete"
    state: touch
  delegate_to: 127.0.0.1
  tags:
    - configure-confirm
