%YAML 1.1
---

- name: determine if this is first run
  stat:
    path: "{{ inventory_dir }}/.setup-complete"
    follow: yes
    get_attributes: no
    get_checksum: no
    get_mime: no
  register: setup_stat
  delegate_to: 127.0.0.1
  tags:
    - setup-check

- name: run setup
  import_tasks: first_run.yml
  when:
    - setup_stat.stat.exists is defined
    - not setup_stat.stat.exists
  tags:
    - initial
