%YAML 1.1
---

- name: determine if this is first run
  stat:
    path: "{{ app_dir }}/.setup-complete"
    follow: yes
    get_attributes: no
    get_checksum: no
    get_mime: no
  register: setup_stat
  tags:
    - setup-check

- name: run setup
  import_tasks: first_run.yml
  when:
    - setup_stat.stat.exists is defined
    - not setup_stat.stat.exists
  tags:
    - initial

- name: create data_dir
  become: yes
  file:
    path: /var/lib/validator
    state: directory
    owner: "{{ user['name'] }}"
    group: "{{ user['name'] }}"

- name: copy over requirements.txt
  become: yes
  copy:
    src: "{{ inventory_dir }}/files/requirements.txt"
    dest: "{{ app_dir }}/requirements.txt"
    owner: "{{ user['name'] }}"
    group: "{{ user['name'] }}"

- name: install validator using pip
  become: yes
  become_user: "{{ user['name'] }}"
  pip:
    virtualenv: "{{ user['home'] }}/venv"
    requirements: "{{ app_dir }}/requirements.txt"
    state: latest
  tags:
    - validator-update
  notify: restart gunicorn

- name: install validator configuration
  become: yes
  template:
    src: validator.cfg.j2
    dest: "{{ app_dir }}/validator.cfg"
