%YAML 1.1
---

- name: determine if this is first run
  stat:
    path: "{{ inventory_dir }}/.setup-complete"
    follow: yes
    get_attributes: no
    get_checksum: no
    get_mime: no
  register: setup_stat
  delegate_to: 127.0.0.1
  tags:
    - setup-check

- name: run setup
  import_tasks: first_run.yml
  when:
    - setup_stat.stat.exists is defined
    - not setup_stat.stat.exists
  tags:
    - initial

- name: copy over validator repo
  become: yes
  synchronize:
    src: "{{ main_dir }}/validator/"
    dest: "{{ app_dir }}"
    set_remote_user: no
    use_ssh_args: yes
  tags:
    - validator-update

- name: fix permissions
  become: yes
  file:
    path: "{{ app_dir }}"
    owner: "{{ user['name'] }}"
    group: "{{ user['group'] }}"
    recurse: yes
  tags:
    - permissions
    - validator

- name: restart services
  become: yes
  service:
    name: "{{ service }}"
    state: restarted
  loop:
    - nginx
    - gunicorn
  tags:
    - validator
