%YAML 1.1
---

- name: determine if this is first run
  stat:
    path: "{{ inventory_dir }}/.setup-complete"
    follow: yes
    get_attributes: no
    get_checksum: no
    get_mime: no
  register: setup_stat
  delegate_to: 127.0.0.1
  tags:
    - setup-check

- name: run setup
  import_tasks: first_run.yml
  when:
    - setup_stat.stat.exists is defined
    - not setup_stat.stat.exists
  tags:
    - initial

- name: copy over validator repo
  become: yes
  synchronize:
    src: "{{ main_dir }}/validator/"
    dest: "{{ app_dir }}"
    set_remote_user: no
    use_ssh_args: yes
  tags:
    - validator-update
  when:
    - validator_vers is undefined
  notify: restart gunicorn

- name: install validator using pip
  become: yes
  pip:
    state: present
    version: "{{ validator_vers }}"
    virtualenv: "{{ user['home'] }}/venv" 
    name: response-validator
  tags:
    - validator-update
  when:
    - validator_vers is defined
  notify: restart gunicorn

- name: install additional modules
  become: yes
  become_user: "{{ user['name'] }}"
  command: "{{ user['home'] }}/venv/bin/python -m nltk.downloader {{ module }}"
  changed_when: False
  loop:
    - snowball_data
    - words
    - stopwords
    - punkt
  loop_control:
    loop_var: module
  when:
    - validator_vers is defined
  tags:
    - validator-setup

- name: fix permissions
  become: yes
  file:
    path: "{{ user['home'] }}"
    owner: "{{ user['name'] }}"
    group: "{{ user['group'] }}"
    recurse: yes
  tags:
    - permissions
    - validator
